# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ElitePython',
                'doc_host': 'https://BrunodsLilly.github.io',
                'git_url': 'https://github.com/BrunodsLilly/ElitePython',
                'lib_path': 'ElitePython'},
  'syms': {'ElitePython.core': {'ElitePython.core.foo': ('core.html#foo', 'ElitePython/core.py')}}}
