"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_data_structures.ipynb.

# %% auto 0
__all__ = ['foo', 'say_hello']

# %% ../nbs/01_data_structures.ipynb 9
def foo():
    """A sample function"""
    pass

# %% ../nbs/01_data_structures.ipynb 10
def say_hello(to: str) -> str:
    """
    Args:
    
        to (str): Name to say hi to.
    """
    return f"Hello {to}!"
